=== ahmedstahoun/XML/lab3/part 1/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="5th settelement,"/>
				<xs:enumeration value="moharram bek,"/>
				<xs:enumeration value="sharq,"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="buildingNumber"/>
				<xs:element ref="Region"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="buildingNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="5,"/>
				<xs:enumeration value="66,"/>
				<xs:enumeration value="7,"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexandria,"/>
				<xs:enumeration value="New Cairo,"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt."/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ali@gmail.com"/>
				<xs:enumeration value="tahoun@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Ali"/>
				<xs:enumeration value="Tahoun"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
								<xs:enumeration value="work"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="abu bakr,"/>
				<xs:enumeration value="moharam bek,"/>
				<xs:enumeration value="wabour elmaya,"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:int">
			<xs:enumeration value="105679511"/>
			<xs:enumeration value="1124369874"/>
			<xs:enumeration value="125675974"/>
			<xs:enumeration value="14569791"/>
			<xs:enumeration value="31123468"/>
			<xs:enumeration value="349675421"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ahmedstahoun/XML/lab3/part 1/employees.xml
<?xml-stylesheet type="text/css" href="employees.css"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/iti/XML/labs/lab3/New%20folder/employees.xsd">
	<employee>
		<name>Tahoun</name>
		<phones>
			<phone type="home">031123468</phone>
			<phone type="work">014569791</phone>
			<phone type="mobile">0125675974</phone>
		</phones>
		<addresses>
			<address>
				<street>moharam bek,</street>
				<buildingNumber>66,</buildingNumber>
				<Region>moharram bek,</Region>
				<city>Alexandria,</city>
				<country>Egypt.</country>
			</address>
			<address>
				<street>wabour elmaya,</street>
				<buildingNumber>7,</buildingNumber>
				<Region>sharq,</Region>
				<city>Alexandria,</city>
				<country>Egypt.</country>
			</address>
		</addresses>
		<email>tahoun@gmail.com</email>
	</employee>
	<employee>
		<name>Ali</name>
		<phones>
			<phone type="home">0349675421</phone>
			<phone type="work">01124369874</phone>
			<phone type="mobile">0105679511</phone>
		</phones>
		<addresses>
			<address>
				<street>abu bakr,</street>
				<buildingNumber>5,</buildingNumber>
				<Region>5th settelement,</Region>
				<city>New Cairo,</city>
				<country>Egypt.</country>
			</address>
		</addresses>
		<email>ali@gmail.com</email>
	</employee>
</employees>
